services:
  db:
    image: postgres:14.18
    container_name: mohstore_db
    env_file: .env.deploy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/scripts/:/docker-entrypoint-initdb.d


  rust_app:
    image: moh_store/latest
    container_name: mohstore_server
    build:
      context: ../
      dockerfile: rocket_api/Dockerfile
    env_file: .env.deploy
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /usr/local/bin/store_server

volumes:
  postgres_data: